apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: extractor
spec:
  tasks:
    - name : prepare-release
      taskRef:
        name : prepare-release
    - name: extract-binaries
      taskRef:
        name: extract-binaries
