apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: extractor
spec:
  tasks:
  - name: prepare-release
    taskRef:
      resolver: bundles
      params:
      - name: bundle
	value: quay.io/dfodor/extracting-bundle@sha256:e5bf14d05789acaac25f80e5a91bbd68e74bce90e37db0642736fcda3d1c50ce 
      - name: name
	value: prepare-release
      - name: kind
	value: task
  - name: extract-binaries
    taskRef:
      resolver: bundles
      params:
      - name: bundle
	value: quay.io/dfodor/extracting-bundle@sha256:e5bf14d05789acaac25f80e5a91bbd68e74bce90e37db0642736fcda3d1c50ce
      - name: name
	value: extract-binaries
      - name: kind
	value: task
