apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: extracting-pipeline
spec:
  tasks:
  - name: prepare-release
    taskRef:
      resolver: bundles
      params:
      - name: bundle
        value: quay.io/dfodor/extracting-bundle@sha256:e5bf14d05789acaac25f80e5a91bbd68e74bce90e37db0642736fcda3d1c50ce
      - name: name
        value: prepare-release
      - name: kind
        value: task
      - name: version
        value: 13.0
      - name: release-notes
        type: string
      - name: branch
        type: string
      - name: repo
        value: dfodorRH/terraform-provider-rhcs
      - name: rel_ver
        value: 15.0
  - name: extract-binaries
    taskRef:
      resolver: bundles
      params:
      - name: bundle
        value: quay.io/dfodor/extracting-bundle@sha256:e5bf14d05789acaac25f80e5a91bbd68e74bce90e37db0642736fcda3d1c50ce
      - name: name
        value: extract-binaries
      - name: kind
        value: task
