apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-release
spec:
  params:
    - name: version
      type: string
    - name: release_notes
      type: string
    - name: branch
      type: string
    - name: repo
      type: string
  steps:
    - name: prepare-release
      image: ubi9:latest
      script: |
        #!/usr/bin/env bash
        make prepare_release version=$(params.version)












