apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tf-rhcs-github-release
spec:
#  workspaces:
#    - name: workspace
  params:
    - name: version
      type: string
    - name: release_notes
      type: string
    - name: branch
      type: string
    - name: repo
      type: string
  steps:
    - name: create-release-from-binaries
      image: ubi9:latest
      env:
      - name: HOME
        value: /releases
      script: |
        #!/usr/bin/env bash
        [[ $HOME == /releases ]]
        RUN wget https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.tar.gz && \
        tar -zvxf gh_2.32.1_linux_amd64.tar.gz && \
        mv gh_2.32.1_linux_amd64/bin/gh /bin/gh && \
        chmod +x /bin/gh && \
        cd $(workspaces.workspace.path)/releases && \
        gh release create $(params.version) *.zip *.json *.sig --repo $(params.repo)
      env:
        - name: GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token-secret
              key: token
