name: Get Latest Tag

on:
  workflow_dispatch:

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        # Extract the numeric part of the tag
        numeric_tag="${latest_tag#"v"}"
        echo "::set-output name=numeric_tag::$numeric_tag"

    - name: Print numeric tag
      run: echo "Numeric Tag: ${{ steps.get_tag.outputs.numeric_tag }}"
